routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
    // Route::resource('users', 'UserDetailController');
    Route::resource('userdetails', 'App\Http\Controllers\UserDetailController');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'first_name',
        'last_name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Models/UserDetail.php
<?php

namespace App\Models;

use DateTimeInterface;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class UserDetail extends Model
{
    use HasFactory, SoftDeletes;

    public $table = 'user_details';

    protected $casts = [
        'work_experience' => 'array',
        'organization' => 'array',
    ];

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected function serializeDate(DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }

    protected $fillable = ['user_id', 'first_name', 'last_name', 'email', 'work_experience', 'organization'];

    public function user()
    {
        return $this->hasOne(User::class, 'id', 'user_id');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('pages.users.index');
    }
}

app/Http/Controllers/UserDetailController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreUserDetailRequest;
use App\Models\UserDetail;
use Illuminate\Database\QueryException;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Yajra\DataTables\Facades\DataTables;

class UserDetailController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $query = UserDetail::where('user_id', Auth::user()->id)->select(sprintf('%s.*', (new UserDetail())->table));
            $table = DataTables::of($query);

            $table->addColumn('actions', '&nbsp;');

            $table->editColumn('actions', function ($row) {
                $viewGate = '';
                $editGate = 'user_edit';
                $deleteGate = '';
                $crudRoutePart = 'userdetails';

                return view('partials.datatablesActions', compact(
                    'viewGate',
                    'editGate',
                    'deleteGate',
                    'crudRoutePart',
                    'row'
                ));
            });

            $table->editColumn('id', function ($row) {
                return $row->id ? $row->id : '';
            });
            $table->editColumn('first_name', function ($row) {
                return $row->first_name ? $row->first_name : '';
            });
            $table->editColumn('last_name', function ($row) {
                return $row->last_name ? $row->last_name : '';
            });
            $table->editColumn('email', function ($row) {
                return $row->email ? $row->email : '';
            });
            // $table->addColumn('work_experience', function ($row) {
            //     return $row->work_experience ? $row->work_experience : '';
            // });
            // $table->addColumn('organization', function ($row) {
            //     return $row->organization ? $row->organization : '';
            // });

            $table->rawColumns(['actions']);

            return $table->make(true);
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pages.users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreUserDetailRequest $request)
    {
        try {
            UserDetail::create($request->all());
            return redirect()->route('home')->with('message', 'User details added.');
        } catch (QueryException $e) {
            return redirect()->route('home')->with('message', 'Server Error!');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        try {
            $userDetail = UserDetail::find($id);
            return view('pages.users.edit', compact('userDetail'));
        } catch (QueryException $e) {
            return redirect()->route('home')->with('message', 'Server Error!');
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try {
            $userDetail = UserDetail::find($id);
            $userDetail->update($request->all());
            return redirect()->route('home')->with('message', 'User details updated.');
        } catch (QueryException $e) {
            return redirect()->route('home')->with('message', 'Server Error!');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Profile App') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" rel="stylesheet" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/datepicker/1.0.10/datepicker.min.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Profile App') }}
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav me-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ms-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->first_name .' '. Auth::user()->last_name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/datepicker/1.0.10/datepicker.min.js"></script>
    @yield('scripts')
</body>
</html>

resources/views/pages/users/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header d-flex justify-content-between align-items-center">
                    {{ __('Add User Details') }}
                </div>

                <div class="card-body">

                    <form method="POST" action="{{ route('userdetails.store') }}">
                        @csrf

                        <input type="hidden" name="user_id" value="{{Auth::user()->id}}">
                        <div class="row mb-3">
                            <label for="first_name" class="col-md-2 col-form-label text-md-end">{{ __('First Name') }}</label>

                            <div class="col-md-9">
                                <input id="first_name" type="text" class="form-control @error('first_name') is-invalid @enderror" name="first_name" value="{{ old('first_name') }}" required autocomplete="first_name" autofocus>

                                @error('first_name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="row mb-3">
                            <label for="last_name" class="col-md-2 col-form-label text-md-end">{{ __('Last Name') }}</label>

                            <div class="col-md-9">
                                <input id="last_name" type="text" class="form-control @error('last_name') is-invalid @enderror" name="last_name" value="{{ old('last_name') }}" required autocomplete="last_name" autofocus>

                                @error('last_name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="row mb-3">
                            <label for="email" class="col-md-2 col-form-label text-md-end">{{ __('Email') }}</label>

                            <div class="col-md-9">
                                <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" required autocomplete="email">

                                @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="row mb-3">
                            <label for="work_experience" class="col-md-2 col-form-label text-md-end">{{ __('Work Experience') }}</label>

                            <div class="col-md-9">
                                <table class="table table-bordered" id="workExperienceAddRemove">
                                    <tr>
                                        <th>Company</th>
                                        <th>Title or Role</th>
                                        <th>Start Date</th>
                                        <th>End Date</th>
                                        <th>Description</th>
                                        <th>Action</th>
                                    </tr>
                                    <tr>
                                        <td><input type="text" name="work_experience[0][company]" placeholder="Enter company" class="form-control" required /></td>
                                        <td><input type="text" name="work_experience[0][title]" placeholder="Enter title" class="form-control" required /></td>
                                        <td><input type="text" name="work_experience[0][start_date]" class="form-control start_date" required readonly/></td>
                                        <td>
                                            <input type="text" name="work_experience[0][end_date]" class="form-control end_date d-none" readonly/>
                                            <div class="d-block">
                                                <input type="checkbox" name="work_experience[0][current_job]" class="current_job" value="1" checked/>
                                                <label class="">Current job</label>
                                            </div>
                                        </td>
                                        <td><textarea class="form-control" type="textarea" name="work_experience[0][description]" placeholder="Enter description" class="form-control"></textarea></td>
                                        <td><button type="button" name="add" id="add-btn" class="btn btn-success">Add More</button></td>
                                    </tr>
                                </table>
                            </div>
                        </div>

                        <div class="row mb-3">
                            <label for="organization" class="col-md-2 col-form-label text-md-end">{{ __('Organization') }}</label>

                            <div class="col-md-9">
                                <table class="table table-bordered" id="organizationAddRemove">
                                    <tr>
                                        <th>Organization name</th>
                                        <th>Associated as</th>
                                        <th>Start Date</th>
                                        <th>End Date</th>
                                        <th>Description</th>
                                        <th>Action</th>
                                    </tr>
                                    <tr>
                                        <td><input type="text" name="organization[0][name]" placeholder="Enter organization" class="form-control" required /></td>
                                        <td><input type="text" name="organization[0][associated_at]" placeholder="Enter associated at" class="form-control" required /></td>
                                        <td><input type="text" name="organization[0][start_date_organization]" class="form-control start_date" required readonly/></td>
                                        <td>
                                            <input type="text" name="organization[0][end_date_organization]" class="form-control end_date d-none" readonly/>
                                            <div class="d-block">
                                                <input type="checkbox" name="organization[0][current_job_organization]" class="current_job" value="1" checked/>
                                                <label class="">Current job</label>
                                            </div>
                                        </td>
                                        <td><textarea class="form-control" type="textarea" name="organization[0][description]" placeholder="Enter description" class="form-control"></textarea></td>
                                        <td><button type="button" name="add" id="add-btn-organization" class="btn btn-success">Add More</button></td>
                                    </tr>
                                </table>
                            </div>
                        </div>

                        <div class="row mb-0">
                            <div class="col-md-9 offset-md-2">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Save') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('scripts')
<script>
    $(function () {
        addDatePicker();

        var i = 0;
        $("#add-btn").click(function(){
            ++i;
            $("#workExperienceAddRemove").append('<tr><td><input type="text" name="work_experience['+i+'][company]" placeholder="Enter company" class="form-control" /></td><td><input type="text" name="work_experience['+i+'][title]" placeholder="Enter title" class="form-control" /></td><td><input type="text" name="work_experience['+i+'][start_date]" class="form-control start_date" readonly/></td><td><input type="text" name="work_experience['+i+'][end_date]" class="form-control end_date d-none" readonly/><div class="d-block"><input type="checkbox" name="work_experience['+i+'][current_job]" class="current_job" value="1" checked/><label class="">Current job</label></div></td><td><textarea class="form-control" type="textarea" name="work_experience['+i+'][description]" placeholder="Enter description" class="form-control"></textarea></td><td><button type="button" class="btn btn-danger remove-tr">Remove</button></td></tr>');
            addDatePicker();
        });

        $(document).on('click', '.remove-tr', function(){
            $(this).parents('tr').remove();
        });

        var i = 0;
        $("#add-btn-organization").click(function(){
            ++i;
            $("#organizationAddRemove").append('<tr><td><input type="text" name="organization['+i+'][name]" placeholder="Enter company" class="form-control" /></td><td><input type="text" name="organization['+i+'][associated_at]" placeholder="Enter title" class="form-control" /></td><td><input type="text" name="organization['+i+'][start_date_organization]" class="form-control start_date" readonly/></td><td><input type="text" name="organization['+i+'][end_date_organization]" class="form-control end_date d-none" readonly/><div class="d-block"><input type="checkbox" name="organization['+i+'][current_job_organization]" class="current_job" value="1" checked/><label class="">Current job</label></div></td><td><textarea class="form-control" type="textarea" name="organization['+i+'][description]" placeholder="Enter description" class="form-control"></textarea></td><td><button type="button" class="btn btn-danger remove-tr-organization">Remove</button></td></tr>');
            addDatePicker();
        });

        $(document).on('click', '.remove-tr-organization', function(){
            $(this).parents('tr').remove();
        });

        $(document).on('click', '.current_job', function() {
            let isChecked = $(this).prop('checked');

            if (isChecked) {
                // $(this).parent().addClass('d-block').removeClass('d-none');
                $(this).parent().parent().find('.end_date').addClass('d-none').removeClass('d-block');
            } else {
                // $(this).parent().addClass('d-none').removeClass('d-block');
                $(this).parent().parent().find('.end_date').addClass('d-block').removeClass('d-none');
            }
        });
    });

    function addDatePicker() {
        $(".start_date").datepicker({
            format: "yyyy-mm",
            viewMode: "months",
            minViewMode: "months",
            startDate: new Date(),
            autoclose: true,
        });
        $(".end_date").datepicker({
            format: "yyyy-mm",
            viewMode: "months",
            minViewMode: "months",
            startDate: new Date(),
            autoclose: true,
        });
    }
</script>
@endsection

resources/views/pages/users/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            @if(session()->has('message'))
                <div class="alert alert-success">
                    {{ session()->get('message') }}
                </div>
            @endif
            <div class="card">
                <div class="card-header d-flex justify-content-between align-items-center">
                    <div>{{ __('User Details') }}</div>
                    <a class="btn btn-xs btn-success" href="{{ route('userdetails.create') }}">
                        Add +
                    </a>
                </div>

                <div class="card-body">
                    <table class=" table table-bordered table-striped table-hover ajaxTable datatable datatable-Ad">
                        <thead>
                            <tr>
                                <th>
                                    ID
                                </th>
                                <th>
                                    First Name
                                </th>
                                <th>
                                    Last Name
                                </th>
                                <th>
                                    Email
                                </th>
                                {{-- <th>
                                    Work Experience
                                </th>
                                <th>
                                    Organization
                                </th> --}}
                                <th>
                                    &nbsp;
                                </th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('scripts')
<script>
    $(function () {
        let dtOverrideGlobals = {
            processing: true,
            serverSide: true,
            retrieve: true,
            aaSorting: [],
            ajax: "{{ route('userdetails.index') }}",
            columns: [
                { data: 'id', name: 'id' },
                { data: 'first_name', name: 'first_name' },
                { data: 'last_name', name: 'last_name' },
                { data: 'email', name: 'email' },
                // { data: 'work_experience', name: 'work_experience', sortable: false, searchable: false },
                // { data: 'organization', name: 'organization', sortable: false, searchable: false },
                { data: 'actions', name: 'Actions', sortable: false, searchable: false }
            ],
            orderCellsTop: true,
            order: [[ 1, 'desc' ]],
            pageLength: 100,
        };
        let table = $('.datatable-Ad').DataTable(dtOverrideGlobals);
        $('a[data-toggle="tab"]').on('shown.bs.tab click', function(e){
            $($.fn.dataTable.tables(true)).DataTable().columns.adjust();
        });
    });
</script>
@endsection

resources/views/partials/datatablesActions.blade.php
@if($viewGate)
    <a class="btn btn-xs btn-primary" href="{{ route($crudRoutePart . '.show', $row->id) }}">
        View
    </a>
@endif

@if($editGate)
    <a class="btn btn-xs btn-info" href="{{ route($crudRoutePart . '.edit', $row->id) }}">
        Edit
    </a>
@endif

@if($deleteGate)
    <form action="{{ route($crudRoutePart . '.destroy', $row->id) }}" method="POST" onsubmit="return confirm('Are you sure you want to delete this?');" style="display: inline-block;">
        <input type="hidden" name="_method" value="DELETE">
        <input type="hidden" name="_token" value="{{ csrf_token() }}">
        <input type="submit" class="btn btn-xs btn-danger" value="Delete">
    </form>
@endif